version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-}
      MYSQL_DATABASE: ${DB_NAME:-market_data}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  collector:
    build: .
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-}
      DB_NAME: ${DB_NAME:-market_data}
      FETCH_INTERVAL: ${FETCH_INTERVAL:-3600}
      HISTORY_START_DATE: ${HISTORY_START_DATE:-2017-07-01}
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: 